<?php

namespace App\FactureYaTimbradoBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('factureya_timbrado');

        $treeBuilder->getRootNode()
            ->children()
                ->scalarNode('endpoint')
                    ->defaultValue('https://www.factureya.com/WS/Facturacion40.svc')
                    ->info('Endpoint del servicio SOAP de FactureYa')
                ->end()
                ->scalarNode('endpoint_pruebas')
                    ->defaultValue('https://demo.factureya.com/WS/Facturacion40.svc')
                    ->info('Endpoint para pruebas de FactureYa')
                ->end()
                ->scalarNode('usuario')
                    ->isRequired()
                    ->cannotBeEmpty()
                    ->info('Usuario de FactureYa')
                ->end()
                ->scalarNode('password')
                    ->isRequired()
                    ->cannotBeEmpty()
                    ->info('Contraseña de FactureYa')
                ->end()
                ->scalarNode('rfc_emisor')
                    ->info('RFC del emisor (opcional, se puede especificar en cada operación)')
                ->end()
                ->booleanNode('modo_pruebas')
                    ->defaultTrue()
                    ->info('Usar endpoints de pruebas')
                ->end()
                ->booleanNode('debug')
                    ->defaultValue('%kernel.debug%')
                    ->info('Habilitar modo debug para logging detallado')
                ->end()
                ->integerNode('timeout')
                    ->defaultValue(30)
                    ->min(10)
                    ->info('Timeout en segundos para las peticiones SOAP')
                ->end()
                ->arrayNode('soap_options')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('trace')
                            ->defaultTrue()
                            ->info('Habilitar tracing de peticiones SOAP')
                        ->end()
                        ->booleanNode('exceptions')
                            ->defaultTrue()
                            ->info('Habilitar excepciones SOAP')
                        ->end()
                        ->scalarNode('connection_timeout')
                            ->defaultValue(30)
                            ->info('Timeout de conexión')
                        ->end()
                        ->scalarNode('ssl_verify_peer')
                            ->defaultTrue()
                            ->info('Verificar certificado SSL')
                        ->end()
                        ->scalarNode('ssl_verify_peer_name')
                            ->defaultTrue()
                            ->info('Verificar nombre del certificado SSL')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('notificaciones')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('email')
                            ->info('Email para notificaciones de timbrado')
                        ->end()
                        ->scalarNode('webhook_url')
                            ->info('URL para webhook de notificaciones')
                        ->end()
                        ->booleanNode('enviar_email_cliente')
                            ->defaultFalse()
                            ->info('Enviar email al cliente automáticamente')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('almacenamiento')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('directorio_xml')
                            ->defaultValue('%kernel.project_dir%/var/factureya/xml')
                            ->info('Directorio para almacenar XMLs')
                        ->end()
                        ->scalarNode('directorio_pdf')
                            ->defaultValue('%kernel.project_dir%/var/factureya/pdf')
                            ->info('Directorio para almacenar PDFs')
                        ->end()
                        ->booleanNode('guardar_localmente')
                            ->defaultTrue()
                            ->info('Guardar archivos localmente')
                        ->end()
                    ->end()
                ->end()
            ->end()
        ;

        return $treeBuilder;
    }
}
